### PR TITLE
Eliminate leftovers from OpenBLAS

### PR DESCRIPTION
**Pull request by IvanUkhov**

### CODE REVIEW

**Comment by emberian** [comment]
Woops, I actually fixed this last night but forgot to push...

**Comment by IvanUkhov** [comment]
With all the changes, I am still not able to plug this provider into [`blas`](https://github.com/stainless-steel/blas). There is a problem with static linking.

**Comment by IvanUkhov** [comment]
If you just clone `libblas-sys`, temporary switch the default provider to `netlib`, and run the test, you’ll get something like:

```
Undefined symbols for architecture x86_64:
  "_cblas_dgemv", referenced from:
      linking::h8fa89248db522ca3faa in lib-44e2fe1a12daab40.o
ld: symbol(s) not found for architecture x86_64
```

**Comment by emberian** [comment]
Yeah, I'm trying to debug it now.

**Comment by emberian** [comment]
Should be fixed now, publishing a new version.

**Pull request merged**
